### ISSUE TITLE
Errors after initial setup

### ISSUE THREAD

**Issue by nanthony21** [TotalJTM/PyPavlovUpdater#4]
I went to settings and entered my info. Got a message saying that the mod path and api key had been saved.

When I click "Open Download Menu" I get a message saying "exceptions". When I try to open "Subscribed Mod Manager" I get a popup:
![image](https://github.com/TotalJTM/PyPavlovUpdater/assets/8433487/ad7f1d9d-e938-4411-bf72-34a528909052)

I'd recommend making use of the built-in [logging](https://docs.python.org/3/library/logging.html) module so you can automatically save a log file with exception stack traces.

**Comment by TotalJTM** [comment]
Thanks, Im going to try to get a new version out today with logging.

**Comment by TotalJTM** [comment]
Pushed new version of program with logging. I probably havent fixed your issue so, if you decide to update the program, let me know if it works for you and send the log over if it doesnt. Thank you for your time.

**Comment by nanthony21** [comment]
```
2023-10-29 01:19:35,400 Version 1.2
2023-10-29 01:19:35,408 Starting new HTTPS connection (1): api.github.com:443
2023-10-29 01:19:36,504 https://api.github.com:443 "GET /repos/TotalJTM/PyPavlovUpdater/releases/latest HTTP/1.1" 200 1224
2023-10-29 01:19:38,763 Starting new HTTPS connection (1): api.mod.io:443
2023-10-29 01:19:39,876 https://api.mod.io:443 "GET /v1/me/subscribed?game_id=3959 HTTP/1.1" 200 None
2023-10-29 01:19:44,073 Starting new HTTPS connection (1): api.mod.io:443
2023-10-29 01:19:45,112 https://api.mod.io:443 "GET /v1/me/subscribed?game_id=3959 HTTP/1.1" 200 None
2023-10-29 01:19:45,115 Exception in main loop
Traceback (most recent call last):
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 656, in <module>
    ret = mainmenu(settings, pavlov_updater)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 479, in mainmenu
    subscribed_window = make_sub_mod_window(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 151, in make_sub_mod_window
    mods = get_subscribed_mods(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 42, in get_subscribed_mods
    update_subscribed_mods(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 29, in update_subscribed_mods
    subscribed_mods = pvu.get_subscribed_modlist()
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater.py", line 206, in get_subscribed_modlist
    total_pages = int(init_resp['result_total']/init_resp['result_count'])+1
ZeroDivisionError: division by zero
```

This is after trying to open the "subscribed mod manager". I don't currently have any subscriptions . It looks like trying to open the download manager still just prints a generic "exception" message to stdout.

**Comment by TotalJTM** [comment]
Just released version 1.3 which implements a fix for this. The program still shows some basic exception messages, but I should only need the log output in the future. I'm closing this issue since the issue should be fixed. Thank you again for reporting this.

**Comment by nanthony21** [comment]
New error message but still not able to open either window. Both buttons now result in this error:
```
Traceback (most recent call last):
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 467, in mainmenu
    download_window = make_download_window(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 192, in make_download_window
    subbed_mods = get_subscribed_mods(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 36, in get_subscribed_mods
    update_subscribed_mods(pvu)
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater_gui.py", line 23, in update_subscribed_mods
    subscribed_mods = pvu.get_subscribed_modlist()
  File "C:\Users\nicke\Documents\git\PyPavlovUpdater\pypavlovupdater\pavlovupdater.py", line 173, in get_subscribed_modlist
    self.logger.info(f'No result: total = {rt}, count = {rc}')
UnboundLocalError: local variable 'rc' referenced before assignment
```

**Comment by TotalJTM** [comment]
Though I fixed this but I introduced a new error. I updated the executable but havent made a release of the code. Ill keep this open and close it after the code to fix it is merged.

**Comment by nanthony21** [comment]
FYI, I can just update through Git, so no need to release a new .exe if it's just for testing.

**Comment by TotalJTM** [comment]
Issue should be fixed now
